/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartGUI.java
 *
 * Created on 07-04-2010, 16:38:10
 */

package presentation;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Zagadka
 */
public class StartGUI extends javax.swing.JFrame {

    private String metodeChoose;



    /** Creates new form StartGUI */
    public StartGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LavOrdre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jstartloc = new javax.swing.JTextField();
        jendLoc = new javax.swing.JTextField();
        jendDate = new javax.swing.JTextField();
        jvolume = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jweight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LavOrdre.setText("Lav Ordre");
        LavOrdre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LavOrdreActionPerformed(evt);
            }
        });

        jLabel1.setText("Laver en ordre");

        jstartloc.setText("Odense");
        jstartloc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstartlocActionPerformed(evt);
            }
        });

        jendLoc.setText("Amsterdam");

        jendDate.setText("2010-05-04");

        jvolume.setText("4000");

        jLabel2.setText("startLoc");

        jLabel3.setText("endLoc");

        jLabel4.setText("endDate");

        jLabel5.setText("volume");

        jweight.setText("800");

        jLabel6.setText("weight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jweight, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jvolume, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jendLoc, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jstartloc)
                        .addComponent(LavOrdre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jendDate, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LavOrdre)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jstartloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jendLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jvolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jendDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LavOrdreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LavOrdreActionPerformed
        // TODO add your handling code here:
	
	
	ComToServer comToServer = new ComToServer();

	    DateFormat df = new SimpleDateFormat("yyyy-mm-dd");
	    Date endDate = null;
	try {
	    endDate = df.parse(jendDate.getText());
	        } catch (ParseException ex) {
	    Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
		}

	    metodeChoose = "placeOrder";
	    SendObject clientChoose = new SendObject(metodeChoose, jstartloc.getText(),
		   jendLoc.getText(), endDate, jvolume.getText(),
		   jweight.getText());
	try {
	    comToServer.connectToServer(clientChoose);
	} catch (Exception ex) {
	    Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
	}
	

	    
	
    }//GEN-LAST:event_LavOrdreActionPerformed

    private void jstartlocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstartlocActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_jstartlocActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LavOrdre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jendDate;
    private javax.swing.JTextField jendLoc;
    private javax.swing.JTextField jstartloc;
    private javax.swing.JTextField jvolume;
    private javax.swing.JTextField jweight;
    // End of variables declaration//GEN-END:variables

}
