/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartGUI.java
 *
 * Created on 07-04-2010, 16:38:10
 */

package presentation;

import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Zagadka
 */
public class StartGUI extends javax.swing.JFrame {

    /** Creates new form StartGUI */
    public StartGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LavOrdre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LavOrdre.setText("Lav Ordre");
        LavOrdre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LavOrdreActionPerformed(evt);
            }
        });

        jLabel1.setText("Laver en ordre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LavOrdre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LavOrdre)
                    .addComponent(jLabel1))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LavOrdreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LavOrdreActionPerformed
        // TODO add your handling code here:
	System.out.println("sdsdsd");
	ConnectServer connectServer = new ConnectServer();
	try {
	    connectServer.conServer();
	} catch (Exception ex) {
	    Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
	}
    }//GEN-LAST:event_LavOrdreActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LavOrdre;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
